import express from 'express';
import { protect } from '../middleware/authMiddleware.js';
import { addToCart, getCart, removeFromCart, updateCart } from '../controllers/cartController.js';
const router = express.Router();
router.use(protect);
router.get('/', getCart);
router.post('/add', addToCart);
router.put('/update', updateCart);
router.delete('/remove/:productId', removeFromCart);
export default router;
